create table T_FF_DF_WORKFLOWDEF (ID VARCHAR(50) not null, definition_type VARCHAR(50) not null, PROCESS_ID VARCHAR(100) not null, NAME VARCHAR(100) not null, DISPLAY_NAME VARCHAR(128), DESCRIPTION VARCHAR(1024), VERSION INTEGER not null, STATE BIT not null, UPLOAD_USER VARCHAR(50), UPLOAD_TIME DATETIME, PUBLISH_USER VARCHAR(50), PUBLISH_TIME DATETIME, PROCESS_CONTENT TEXT,EXTENDTYPE VARCHAR(100) ,primary key (ID));

create table T_FF_HIST_TRACE (ID VARCHAR(50) not null, PROCESSINSTANCE_ID VARCHAR(50) not null, STEP_NUMBER INTEGER not null, MINOR_NUMBER INTEGER not null, TYPE VARCHAR(15) not null, EDGE_ID VARCHAR(100), FROM_NODE_ID VARCHAR(100) not null, TO_NODE_ID VARCHAR(100) not null, primary key (ID));

create table T_FF_RT_PROCESSINSTANCE (ID VARCHAR(50) not null, PROCESS_ID VARCHAR(100) not null, VERSION INTEGER not null, NAME VARCHAR(100), DISPLAY_NAME VARCHAR(128), STATE INTEGER not null, SUSPENDED BIT not null, CREATOR_ID VARCHAR(50), CREATED_TIME DATETIME, STARTED_TIME DATETIME, EXPIRED_TIME DATETIME, END_TIME DATETIME, PARENT_PROCESSINSTANCE_ID VARCHAR(50), PARENT_TASKINSTANCE_ID VARCHAR(50), primary key (ID));

create table T_FF_RT_PROCINST_VAR (PROCESSINSTANCE_ID VARCHAR(50) not null, VALUE VARCHAR(255), NAME VARCHAR(255) not null, primary key (PROCESSINSTANCE_ID, NAME));

create table T_FF_RT_TASKINSTANCE (ID VARCHAR(50) not null, BIZ_TYPE VARCHAR(250) not null, TASK_ID VARCHAR(300) not null, ACTIVITY_ID VARCHAR(200) not null, NAME VARCHAR(100) not null, DISPLAY_NAME VARCHAR(128), STATE INTEGER not null, SUSPENDED INTEGER not null, TASK_TYPE VARCHAR(10), CREATED_TIME DATETIME not null, STARTED_TIME DATETIME, EXPIRED_TIME DATETIME, END_TIME DATETIME, ASSIGNMENT_STRATEGY VARCHAR(10), PROCESSINSTANCE_ID VARCHAR(50) not null, PROCESS_ID VARCHAR(100) not null, VERSION INTEGER not null, TARGET_ACTIVITY_ID VARCHAR(100), FROM_ACTIVITY_ID VARCHAR(600), STEP_NUMBER INTEGER not null, CAN_BE_WITHDRAWN BIT not null, primary key (ID));

create table T_FF_RT_TOKEN (ID VARCHAR(50) not null, ALIVE BIT not null, VALUE INTEGER not null, NODE_ID VARCHAR(200) not null, PROCESSINSTANCE_ID VARCHAR(50) not null, STEP_NUMBER INTEGER not null, FROM_ACTIVITY_ID VARCHAR(100), primary key (ID));

create table T_FF_RT_WORKITEM (ID VARCHAR(50) not null, STATE INTEGER not null, CREATED_TIME DATETIME not null, CLAIMED_TIME DATETIME, END_TIME DATETIME, ACTOR_ID VARCHAR(50), COMMENTS VARCHAR(1024), TASKINSTANCE_ID VARCHAR(50) not null, primary key (ID));

create index IDX_TRACE_PROCINSTID on T_FF_HIST_TRACE (PROCESSINSTANCE_ID);

alter table T_FF_RT_PROCINST_VAR add constraint FKD79C420D7AF471D8 foreign key (PROCESSINSTANCE_ID) references T_FF_RT_PROCESSINSTANCE;

alter table T_FF_RT_WORKITEM add constraint FK4131554DE2527DDC foreign key (TASKINSTANCE_ID) references T_FF_RT_TASKINSTANCE;